// packages/frontend/src/MeasurementChart.jsx
import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { useTheme } from '@mui/material/styles'
import Paper from '@mui/material/Paper'
import Grid from '@mui/material/Grid'
import FormControl from '@mui/material/FormControl'
import InputLabel from '@mui/material/InputLabel'
import Select from '@mui/material/Select'
import MenuItem from '@mui/material/MenuItem'
import Button from '@mui/material/Button'
import HighchartsReact from 'highcharts-react-official'
import HighStock from 'highcharts/highstock'
import 'highcharts/css/highcharts.css'
import './highcharts.overrides.css'
import useApiClient from './hooks/useApiClient'
import useDarkMode from './hooks/useDarkMode'

const rangeSelectorButtons = [
  {
    count: 6,
    text: '6h',
    type: 'hour',
  },
  {
    count: 12,
    text: '12h',
    type: 'hour',
  },
  {
    text: '1d',
    type: 'day',
  },
  {
    count: 7,
    text: '1w',
    type: 'day',
  },
  {
    text: '1m',
    type: 'month',
  },
  {
    count: 3,
    text: '3m',
    type: 'month',
  },
  {
    count: 6,
    text: '6m',
    type: 'month',
  },
  {
    text: '1y',
    type: 'year',
  },
  {
    type: 'all',
    text: 'All',
  },
]

export default function MeasurementChart() {
  const [isDarkMode] = useDarkMode()
  const dayStart = new Date().setHours(0, 0, 0, 0)
  const dayEnd = new Date().setHours(23, 59, 59, 999)
  const theme = useTheme()
  const [, apiClient] = useApiClient()
  const [aggregation, setAggregation] = useState('average')
  const { search } = useLocation()
  const [types, setTypes] = useState([])
  const [locationsAndTypes, setLocationsAndTypes] = useState([])
  const [extremes, setExtremes] = useState({
    min: dayStart,
    max: dayEnd,
  })
  const [dataSeries, setDataSeries] = useState([])
  const [navigatorSeries, setNavigatorSeries] = useState([])
  const [refetchState, setRefetchState] = useState({})
  const refetchSeries = () => setRefetchState({})

  const yAxis = types.map((type) => ({
    id: type,
    title: {
      text: type,
    },
    maxPadding: 0,
    minPadding: 0,
    showLastLabel: true,
    opposite: false,
  }))

  const isAllSeriesInitialized =
    locationsAndTypes.length === dataSeries.length &&
    locationsAndTypes.length === navigatorSeries.length

  const series = isAllSeriesInitialized
    ? [...dataSeries, ...navigatorSeries]
    : []

  // calculate locations and types from search
  useEffect(() => {
    const urlSearchParams = new URLSearchParams(search)
    const locations = urlSearchParams.getAll('location')
    const types = urlSearchParams.getAll('type')
    const uniqueTypes = [...new Set(types)]

    setTypes(uniqueTypes)
    setLocationsAndTypes(
      locations.map((location, i) => ({
        location,
        type: types[i],
      }))
    )
  }, [search])

  // fetch data series
  useEffect(() => {
    const fetchDataSeries = async () => {
      const newSeries = await Promise.all(
        locationsAndTypes.map(async ({ location, type }) => {
          const startISO = new Date(extremes.min).toISOString()
          const endISO = new Date(extremes.max).toISOString()
          const data = await apiClient(
            `/measurement/location/${location}/type/${type}/from/${startISO}/to/${endISO}/aggregation/${aggregation}`
          )
          return {
            name: `${location} - ${type}`,
            data,
            yAxis: type,
            showInNavigator: false,
          }
        })
      )

      setDataSeries(newSeries)
    }
    if (locationsAndTypes.length) {
      fetchDataSeries().catch(console.error)
    }
  }, [apiClient, locationsAndTypes, extremes, aggregation, types, refetchState])

  // fetch navigator series
  useEffect(() => {
    const fetchNavigatorSeries = async () => {
      const newSeries = await Promise.all(
        locationsAndTypes.map(async ({ location, type }, i) => {
          const data = await apiClient(
            `/measurement/location/${location}/type/${type}`
          )
          return {
            name: `${location} - ${type}`,
            data,
            yAxis: type,
            navigatorOptions: {
              visible: true,
            },
            colorIndex: i,
            showInNavigator: true,
            showInLegend: false,
            visible: false,
          }
        })
      )

      setNavigatorSeries(newSeries)
    }
    if (locationsAndTypes.length) {
      fetchNavigatorSeries().catch(console.error)
    }
  }, [apiClient, locationsAndTypes, types, refetchState])

  return (
    <>
      <h1>Measurements</h1>

      <Paper
        style={{ padding: theme.spacing(2) }}
        className={`highcharts-${isDarkMode ? 'dark' : 'light'}`}
      >
        <HighchartsReact
          containerProps={{ style: { marginBottom: theme.spacing(1) } }}
          highcharts={HighStock}
          constructorType={'stockChart'}
          options={{
            chart: {
              type: 'line',
              animation: false,
              styledMode: true,
              marginTop: 20,
            },
            accessibility: {
              enabled: false,
            },
            plotOptions: {
              series: {
                dataGrouping: {
                  enabled: false,
                },
                animation: false,
              },
            },
            time: {
              timezoneOffset: new Date().getTimezoneOffset(),
            },
            rangeSelector: {
              inputEnabled: false,
              dropdown: 'never',
              buttonPosition: {
                align: 'right',
                y: -10,
              },
              buttons: rangeSelectorButtons,
            },
            xAxis: [
              {
                type: 'datetime',
                ordinal: false,
                min: extremes.min,
                max: extremes.max,
                events: {
                  afterSetExtremes: ({ min, max }) =>
                    setExtremes({
                      min: new Date(min ?? dayStart).getTime(),
                      max: new Date(max ?? dayEnd).getTime(),
                    }),
                },
              },
            ],
            yAxis,
            series,
            tooltip: {
              split: false,
              shared: true,
            },
            legend: {
              enabled: true,
            },
            navigator: {
              xAxis: {
                overscroll: 86400000,
              },
            },
            scrollbar: {
              enabled: true,
              liveRedraw: false,
              buttonsEnabled: true,
              height: 16,
            },
          }}
        />
        <Grid container>
          <Grid item xs={6}>
            <FormControl size="small" color="secondary">
              <InputLabel>Aggregation</InputLabel>
              <Select
                value={aggregation}
                onChange={(e) => setAggregation(e.target.value)}
                label="Aggregation"
              >
                <MenuItem value="average">Average</MenuItem>
                <MenuItem value="minimum">Minimum</MenuItem>
                <MenuItem value="maximum">Maximum</MenuItem>
                <MenuItem value="count">Count</MenuItem>
                <MenuItem value="sum">Sum</MenuItem>
              </Select>
            </FormControl>
          </Grid>
          <Grid item xs={6} style={{ textAlign: 'right' }}>
            <Button
              variant="contained"
              color="secondary"
              onClick={() => refetchSeries()}
            >
              Refresh
            </Button>
          </Grid>
        </Grid>
      </Paper>
    </>
  )
}

// packages/sdc2-frontend-old/src/components/MeasurementChart.vue
<template>
  <div>
    <h3>Measurements</h3>

    <div v-if="chart === null" class="center-align">
      <preloader></preloader>
    </div>

    <div id="chart"></div>

    <div>
      <select
        v-model="aggregationType"
        class="browser-default"
        style="display: inline-block"
      >
        <option value="average">Average</option>
        <option value="minimum">Minimum</option>
        <option value="maximum">Maximum</option>
        <option value="count">Count</option>
        <option value="sum">Sum</option>
      </select>
      <button
        class="btn waves-effect waves-light right"
        @click="refresh"
        :disabled="this.chart === null"
      >
        <i class="material-icons right">refresh</i> Refresh
      </button>
    </div>
  </div>
</template>

<script>
import Highcharts from 'highcharts/highstock'
import axios from 'axios'
import _ from 'lodash'
import Preloader from './Preloader.vue'

export default {
  name: 'MeasurementChart',
  components: {
    Preloader,
  },
  data() {
    return {
      chart: null,
      series: [],
      initializing: true,
      aggregationType: 'average',
    }
  },
  computed: {
    locations() {
      return _.castArray(this.$route.query.location)
    },
    types() {
      return _.castArray(this.$route.query.type)
    },
    uniqueTypes() {
      return _.uniq(this.types)
    },
  },
  watch: {
    aggregationType: function () {
      this.afterSetExtremes()
    },
  },
  methods: {
    async initSeries() {
      const numberOfSeries = this.locations.length
      await Promise.all(
        this.locations.map(async (l, index) => {
          const t = this.types[index]
          const response = await axios.get(
            `/measurement/location/${l}/type/${t}`
          )
          this.series[index] = {
            name: `${l} - ${t}`,
            yAxis: t,
            data: response.data,
            showInNavigator: false,
            showInLegend: true,
            visible: true,
            dataGrouping: {
              enabled: false,
            },
          }
          this.series[index + numberOfSeries] = {
            name: `${l} - ${t}`,
            yAxis: t,
            data: response.data,
            colorIndex: index,
            navigatorOptions: {
              visible: true,
            },
            showInNavigator: true,
            showInLegend: false,
            visible: false,
            dataGrouping: {
              enabled: false,
            },
          }
        })
      )
    },
    async afterSetExtremes() {
      const from = new Date(this.chart.xAxis[0].getExtremes().min).toISOString()
      const to = new Date(this.chart.xAxis[0].getExtremes().max).toISOString()
      this.chart.showLoading('Loading data...')

      await Promise.all(
        this.locations.map(async (l, index) => {
          const t = this.types[index]
          const response = await axios.get(
            `/measurement/location/${l}/type/${t}/from/${from}/to/${to}/aggregation/${this.aggregationType}`
          )
          this.chart.series[index].setData(response.data, false)
        })
      )

      this.chart.redraw()
      this.chart.hideLoading()
    },
    initHighCharts() {
      this.chart = Highcharts.stockChart('chart', {
        rangeSelector: {
          inputEnabled: false,
          buttons: [
            {
              type: 'hour',
              count: 6,
              text: '6h',
            },
            {
              type: 'hour',
              count: 12,
              text: '12h',
            },
            {
              type: 'day',
              count: 1,
              text: '1d',
            },
            {
              type: 'week',
              count: 1,
              text: '1w',
            },
            {
              type: 'day',
              count: 30,
              text: '1m',
            },
            {
              type: 'month',
              count: 3,
              text: '3m',
            },
            {
              type: 'month',
              count: 6,
              text: '6m',
            },
            {
              type: 'all',
              text: 'All',
            },
          ],
        },
        xAxis: {
          type: 'datetime',
          ordinal: false,
          minRange: 3600000,
          events: {
            afterSetExtremes: this.afterSetExtremes,
          },
        },
        colors: [
          '#40c4ff',
          '#37474f',
          '#69f0ae',
          '#ffab40',
          '#7c4dff',
          '#ff4081',
          '#eeff41',
          '#00695c',
          '#ff3d00',
          '#558b2f',
        ],
        chart: {
          animation: false,
        },
        time: {
          useUTC: true,
          timezoneOffset: new Date().getTimezoneOffset(),
        },
        yAxis: this.uniqueTypes.map((t) => {
          return {
            id: t,
            type: 'linear',
            title: {
              text: t,
            },
          }
        }),
        navigator: {
          adaptToUpdatedData: false,
          xAxis: {
            overscroll: 86400000,
          },
        },
        scrollbar: {
          liveRedraw: false,
        },
        plotOptions: {
          series: {
            dataGrouping: {
              enabled: false,
            },
            animation: false,
          },
        },
        tooltip: {
          valueDecimals: 2,
        },
        legend: {
          enabled: true,
        },
        credits: {
          enabled: false,
        },
        series: this.series,
      })
    },
    refresh() {
      this.afterSetExtremes()
    },
  },
  async mounted() {
    await this.initSeries()
    this.initHighCharts()
  },
  updated() {
    if (this.initializing) {
      const start = new Date().setHours(0, 0, 0, 0)
      const end = new Date().setHours(23, 59, 59, 999)
      this.chart.xAxis[0].setExtremes(start, end)
    }
    this.initializing = false
  },
}
</script>

<style scoped>
select {
  display: inline-block;
  max-width: 120px;
  height: 34px;
}
</style>
