// packages/frontend/src/Dashboard.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router'
import { useTheme } from '@mui/material/styles'
import FormControlLabel from '@mui/material/FormControlLabel'
import Checkbox from '@mui/material/Checkbox'
import Button from '@mui/material/Button'
import Table from '@mui/material/Table'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import TableContainer from '@mui/material/TableContainer'
import TableHead from '@mui/material/TableHead'
import TableRow from '@mui/material/TableRow'
import Paper from '@mui/material/Paper'
import Link from '@mui/material/Link'
import Spinner from './Spinner'
import useApiClient from './hooks/useApiClient'
import useDarkMode from './hooks/useDarkMode'

export default function Dashboard() {
  const theme = useTheme()
  const [darkMode] = useDarkMode()
  const [{ data = [], loading }] = useApiClient('/location')
  const [showStale, setShowStale] = useState(false)
  const [selectedItems, setSelectedItems] = useState([])
  const navigate = useNavigate()

  const linkColor = theme.palette.secondary[darkMode ? 'light' : 'dark']

  const visibleItems = showStale ? data : data.filter(({ isStale }) => !isStale)
  const visibleLocations = [
    ...new Set(visibleItems.map(({ location }) => location)),
  ]
  const visibleTypes = [...new Set(visibleItems.map(({ type }) => type))]

  const isValidItem = ({ location, type }) =>
    visibleItems.some(
      ({ location: l, type: t }) => l === location && t === type
    )
  const isSelected = ({ location, type }) =>
    selectedItems.some(
      ({ location: l, type: t }) => l === location && t === type
    )
  const isEveryItemSelected = (filterFunction) =>
    !visibleItems
      .filter(filterFunction)
      .some(
        ({ location, type }) =>
          !selectedItems.some(
            ({ location: l, type: t }) => l === location && t === type
          )
      )
  const selectAll = (filterFunction) => {
    const itemsToSelect = visibleItems
      .filter(filterFunction)
      .filter((i) => !isSelected(i))
    setSelectedItems((selectedItems) => [...selectedItems, ...itemsToSelect])
  }
  const deselectAll = (filterFunction) => {
    setSelectedItems(selectedItems.filter((i) => !filterFunction(i)))
  }
  const toggle = (filterFunction) => {
    if (isEveryItemSelected(filterFunction)) {
      deselectAll(filterFunction)
    } else {
      selectAll(filterFunction)
    }
  }
  const deselectStale = () => {
    const staleItems = data.filter(({ isStale }) => isStale)
    deselectAll(({ location, type }) =>
      staleItems.some(
        ({ location: l, type: t }) => l === location && t === type
      )
    )
  }

  const table = () => {
    if (!data.length && loading) {
      return <Spinner />
    }

    return (
      <>
        <div style={{ textAlign: 'right', marginBottom: theme.spacing(1) }}>
          <FormControlLabel
            control={
              <Checkbox
                name="showStale"
                color="secondary"
                checked={showStale}
                onChange={(e) => {
                  deselectStale()
                  setShowStale(e.target.checked)
                }}
              />
            }
            label="Show stale locations"
          />
        </div>

        <TableContainer component={Paper}>
          <Table size="small" aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell />
                {visibleTypes.map((type) => (
                  <TableCell
                    key={type}
                    style={{
                      textAlign: 'center',
                      padding: theme.spacing(1, 0),
                    }}
                  >
                    <Link
                      href={'#'}
                      onClick={(e) => {
                        e.preventDefault()
                        toggle(({ type: t }) => t === type)
                      }}
                      style={{
                        writingMode: 'vertical-rl',
                        transform: 'rotate(180deg)',
                        textDecoration: 'none',
                        color: linkColor,
                      }}
                    >
                      {type}
                    </Link>
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {visibleLocations.map((location) => (
                <TableRow key={location}>
                  <TableCell
                    component="th"
                    scope="row"
                    style={{ textAlign: 'right' }}
                  >
                    <Link
                      href={'#'}
                      style={{
                        textDecoration: 'none',
                        color: linkColor,
                      }}
                      onClick={(e) => {
                        toggle(({ location: l }) => l === location)
                        e.preventDefault()
                      }}
                    >
                      {location}
                    </Link>
                  </TableCell>
                  {visibleTypes.map((type) => (
                    <TableCell
                      key={type}
                      style={{ textAlign: 'center', padding: 0 }}
                    >
                      {isValidItem({ location, type }) ? (
                        <Checkbox
                          color="secondary"
                          size="small"
                          checked={isSelected({ location, type })}
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedItems((selectedItems) => [
                                ...selectedItems,
                                { location, type },
                              ])
                            } else {
                              setSelectedItems((selectedItems) => [
                                ...selectedItems.filter(
                                  ({ location: l, type: t }) =>
                                    !(l === location && t === type)
                                ),
                              ])
                            }
                          }}
                        />
                      ) : null}
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>

        <div style={{ textAlign: 'right', marginTop: theme.spacing(2) }}>
          <Button
            variant="contained"
            color="secondary"
            disabled={!selectedItems.length}
            onClick={() => {
              const urlSearchParams = new URLSearchParams()
              for (const item of selectedItems) {
                urlSearchParams.append('location', item.location)
                urlSearchParams.append('type', item.type)
              }
              navigate({
                pathname: './measurements',
                search: urlSearchParams.toString(),
              })
            }}
          >
            Show selected measurements
          </Button>
        </div>
      </>
    )
  }

  return (
    <div style={{ maxWidth: 600, margin: '0 auto' }}>
      <h1>Dashboard</h1>

      {table()}
    </div>
  )
}

// packages/sdc2-frontend/src/components/Dashboard.vue
<template>
  <div class="row">
    <div class="col s12 m10 push-m1 l8 push-l2">
      <h3>Dashboard</h3>

      <p class="stale-checkbox">
        <label>
          <input
            type="checkbox"
            v-model="showStale"
            @change="deselectStale()"
          />
          <span>Show stale data</span>
        </label>
      </p>

      <preloader v-if="!items" class="center-align"></preloader>

      <table v-if="items" class="striped highlight centered">
        <thead>
          <tr>
            <th></th>
            <th v-for="type in visibleTypes" :key="type" class="sideways">
              <a href="#" @click.prevent.stop="toggleType(type)">{{ type }}</a>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="location in visibleLocations" :key="location">
            <td>
              <a href="#" @click.prevent.stop="toggleLocation(location)">{{
                location
              }}</a>
            </td>
            <td v-for="type in visibleTypes" :key="`${location}_${type}`">
              <label
                v-if="isValidItem({ location, type })"
                class="dense-checkbox"
              >
                <input
                  type="checkbox"
                  :value="{ location, type }"
                  v-model="selectedItems"
                />
                <span></span>
              </label>
            </td>
          </tr>
        </tbody>
      </table>

      <p class="right-align">
        <button
          class="btn waves-effect waves-light"
          @click="showMeasurements"
          :disabled="selectedItems.length === 0"
        >
          <i class="material-icons right">show_chart</i> Show selected
          measurements
        </button>
      </p>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import _ from 'lodash'
import router from '../router/index'
import Preloader from './Preloader.vue'

export default {
  name: 'Dashboard',
  components: {
    Preloader,
  },
  async mounted() {
    const response = await axios.get('/location')
    this.items = response.data
  },
  data() {
    return {
      selectedItems: [],
      showStale: false,
      items: null,
    }
  },
  computed: {
    visibleItems() {
      if (!this.items) {
        return null
      }
      if (this.showStale) {
        return this.items
      }
      return this.items.filter(({ isStale }) => !isStale)
    },
    visibleLocations() {
      const locations = this.visibleItems.map(({ location }) => location)
      return _.uniq(locations)
    },
    visibleTypes() {
      const types = this.visibleItems.map(({ type }) => type)
      return _.uniq(types)
    },
  },
  methods: {
    showMeasurements() {
      const query = {
        location: this.selectedItems.map(({ location }) => location),
        type: this.selectedItems.map(({ type }) => type),
      }
      router.push({ name: 'MeasurementChart', query })
    },
    isValidItem({ location, type }) {
      return this.items.some(
        ({ location: l, type: t }) => location === l && type === t
      )
    },
    everyItemSelected(filterFunction) {
      const count = this.visibleItems.filter(filterFunction).length
      const selectedCount = this.selectedItems.filter(filterFunction).length
      return count === selectedCount
    },
    deselectAll(filterFunction) {
      const indicesToRemove = this.selectedItems
        .map((item, index) => {
          if (filterFunction(item)) {
            return index
          }
          return null
        })
        .filter(i => i !== null)
      indicesToRemove.reverse().forEach(index => {
        this.selectedItems.splice(index, 1)
      })
    },
    selectAll(filterFunction) {
      const itemsToSelect = this.visibleItems
        .filter(filterFunction)
        .filter(({ location, type }) => {
          return !this.selectedItems.some(
            ({ location: l, type: t }) => location === l && type === t
          )
        })
      itemsToSelect.forEach(({ location, type }) => {
        this.selectedItems.push({ location, type })
      })
    },
    deselectStale() {
      this.deselectAll(({ isStale }) => isStale)
    },
    toggle(filterFunction) {
      const everyItemSelected = this.everyItemSelected(filterFunction)
      if (everyItemSelected) {
        this.deselectAll(filterFunction)
      } else {
        this.selectAll(filterFunction)
      }
    },
    toggleLocation(l) {
      this.toggle(({ location }) => location === l)
    },
    toggleType(t) {
      this.toggle(({ type }) => type === t)
    },
  },
}
</script>

<style scoped>
p.stale-checkbox {
  text-align: right;
  margin: 0;
}

th.sideways a {
  writing-mode: vertical-rl;
  transform: rotate(180deg);
  font-weight: normal;
}

label.dense-checkbox span {
  padding-left: 18px;
}
</style>
